[build]
  publish = "."

# Form settings
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

# Override form success paths
[context.production.environment]
  NETLIFY_FORM_SUCCESS_PATH = "/thank-you"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"